GET http://localhost:5000/users/getCurrentUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjMwMzQzNjQ0NDA5MDI5LCJpYXQiOjE1ODI4ODM3ODZ9.RtWzxZGUvyg00piS4hbHPOfPJwQGsIi58TdZTfeop-Y

###

DELETE  http://localhost:3000/subscribers/5e457fa93df4632cfc027d91

###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "user" : {
        "_id" : "5e5d10051dac40419c98d2f2",
        "Name" : "Mouad",
        "image" : "",
        "email" : "Mouad@gmail.com",
        "id" : 630343644409020,
        "location" : {
            "type": "Point",
            "coordinates": [33.996159,-6.852711]
        },
        "actif": false
    },
    "type" : "Driver"
}

###

PATCH http://localhost:3000/subscribers/5e4577d9dc6aff42b87d8d0c
Content-Type: application/json

{
    "subscribeTo":"TraversyMedia"
}

###

POST http://localhost:5000/users/signin
Content-Type: application/json

{
    "user":{"id": 3456789765435},
    "type": "Customer"
}

###

Post http://localhost:5000/requests/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjMwMzQzNjQ0NDA5MDI5LCJpYXQiOjE1ODI4ODM3ODZ9.RtWzxZGUvyg00piS4hbHPOfPJwQGsIi58TdZTfeop-Y

###
GET http://localhost:5000/requests/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjMwMzQzNjQ0NDA5MDI5LCJpYXQiOjE1ODI4ODM3ODZ9.RtWzxZGUvyg00piS4hbHPOfPJwQGsIi58TdZTfeop-Y
